name: Build nixfra_phx

on:
  push:

jobs:
  package:
    runs-on: self-hosted
    env:
      PATH: /run/wrappers/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
      NIX_PATH: /nix/var/nix/profiles/per-user/root/channels:nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Package
      run: |
        nix/build-package.sh
