name: Build nixfra_phx

on:
  push:

jobs:
  package:
    runs-on: self-hosted
    steps:
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Package
      run: |
        nix/build-package.sh
